"""V2 repaired Development candidate-quality sweep; privileged, not camera data.

The original v2 terminal stays failed. No oracle range is used by any sweep arm.
G0 and G1 keep a9d9eabf scoring; reference_S2 is separately generated by the
unmodified original GPU2 implementation on these new sensor arrays.
"""
import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import hashlib
import json
from pathlib import Path
import time
import numpy as np
from scipy.ndimage import maximum_filter

FAMILY = 'cnh-track-a-scale-v2-20260926'
SEED = 20260928
SPECS = {
    'G1': (0., 0., 0., 0, False),
    'FA1': (0., 0., 0., 1, False), 'FA3': (0., 0., 0., 3, False), 'FA10': (0., 0., 0., 10, False),
    'SHIFT025': (.25, 0., 0., 0, False), 'SHIFT05': (.5, 0., 0., 0, False), 'SHIFT1': (1., 0., 0., 0, False),
    'DILATE05': (0., .5, 0., 0, False), 'DILATE1': (0., 1., 0., 0, False),
    'DROP20': (0., 0., .2, 0, False), 'DROP40': (0., 0., .4, 0, False),
    'COMBO_MODERATE': (.5, .5, .2, 3, False), 'COMBO_SEVERE': (1., 1., .4, 10, False),
    'BGFA1': (0., 0., 0., 1, True), 'BGFA3': (0., 0., 0., 3, True), 'BGFA10': (0., 0., 0., 10, True),
}
ARMS = ('G0', *SPECS, 'G4prime_local')


def build_calibration(root):
    """Bias and footprint size templates use calib only, with no outcome fitting."""
    sensor, geometry = root/'sensor', root/'geometry'
    histograms, templates = [], []
    for unit in range(96, 128):
        data = json.loads((geometry/f'unit{unit:02d}'/f'unit{unit:02d}.json').read_text(encoding='utf-8-sig'))
        assert data['split'] == 'calib'
        with np.load(sensor/f'unit{unit:02d}-mount-10-observations.npz') as f:
            if int(f['rate']) != 5:
                raise ValueError('This diagnostic requires forced 5 Hz inputs')
            histograms.append(f['hist'][1])
            configs = f['config']
        with np.load(sensor/f'unit{unit:02d}-mount-10-oracle.npz') as f:
            oid = f['object_id']
        for c in data['configs']:
            for obj in c['objects']:
                if obj['category'] == 'BACKGROUND':
                    continue
                for row in np.flatnonzero(configs == c['config']):
                    rc = np.argwhere((oid[row] == obj['id']).any(-1))
                    if len(rc):
                        templates.append((rc-rc.min(0)).tolist())
    # Float64 matches the original unit_records -> median calibration path.
    bias = np.median(np.concatenate(histograms).astype(float), axis=0)
    np.save(root/'bias.npy', bias)
    (root/'angular_templates.json').write_text(json.dumps(templates), encoding='utf-8')
    return dict(calib_units=32, templates=len(templates), bias_shape=list(bias.shape))


def to_pixels(xy, direction, shift):
    shifted = np.floor((xy+direction*shift)*16).astype(int)
    valid = ((shifted >= 0) & (shifted < 128)).all(1)
    mask = np.zeros((128, 128), bool)
    col, row = shifted[valid].T
    mask[row, col] = True
    return mask


def to_zones(pixels, dilation=0.):
    if dilation:
        pixels = maximum_filter(pixels, size=2*int(dilation*16)+1, mode='constant', cval=0)
    return pixels.reshape(8, 16, 8, 16).any((1, 3))


def background_support(oid, bg_ids):
    """BACKGROUND zones and actual first-hit boundaries between background IDs."""
    from cnh_route_sensor import angular_rays
    from cnh_track_a_readout import EDGE
    rays, _ = angular_rays(16)
    xy = (rays[..., :2]/rays[..., 2:]+EDGE)/(2*EDGE)*8
    rc = np.floor(xy*16).astype(int)
    image = np.full((128, 128), -1, int)
    image[rc[..., 1], rc[..., 0]] = oid
    bg = np.isin(image, bg_ids)
    edge = np.zeros_like(bg)
    for axis in (0, 1):
        aa, bb = [slice(None)]*2, [slice(None)]*2
        aa[axis], bb[axis] = slice(1, None), slice(None, -1)
        aa, bb = tuple(aa), tuple(bb)
        diff = bg[aa] & bg[bb] & (image[aa] != image[bb])
        edge[aa] |= diff
        edge[bb] |= diff
    return to_zones(bg), to_zones(edge)


def fake_footprints(pool, rng, count, bg=None, edge=None):
    masks, stats = [], dict(requested=count, generated=0, boundary_placed=0, partial_fallback=0, cells=0)
    for _ in range(count):
        template = pool[int(rng.integers(len(pool)))]
        origins = np.array([(y, x) for y in range(8-int(template[:, 0].max()))
                            for x in range(8-int(template[:, 1].max()))])
        if bg is None:
            origin = origins[int(rng.integers(len(origins)))]
            rc = template+origin
        else:
            rc_all = template[None]+origins[:, None]
            fit = bg[rc_all[..., 0], rc_all[..., 1]].all(1)
            on_edge = edge[rc_all[..., 0], rc_all[..., 1]].any(1)
            candidates = np.flatnonzero(fit & on_edge)
            if len(candidates):
                stats['boundary_placed'] += 1
            else:
                candidates = np.flatnonzero(fit)
            if len(candidates):
                rc = rc_all[candidates[int(rng.integers(len(candidates)))]]
            else:
                # Fully occupied foreground can prevent an equal-size background
                # footprint. Preserve the diagnostic, disclose reduced footprint.
                counts = bg[rc_all[..., 0], rc_all[..., 1]].sum(1)
                candidates = np.flatnonzero(counts == counts.max())
                rc = rc_all[candidates[int(rng.integers(len(candidates)))]]
                rc = rc[bg[rc[:, 0], rc[:, 1]]]
                stats['partial_fallback'] += 1
        mask = np.zeros((8, 8), bool)
        if len(rc):
            mask[rc[:, 0], rc[:, 1]] = True
            stats['generated'] += 1
        stats['cells'] += int(mask.sum())
        masks.append(mask)
    return masks, stats


def candidate_masks(oid, objects, unit, config, pool):
    from cnh_route_sensor import angular_rays
    from cnh_track_a_readout import EDGE
    rays, _ = angular_rays(16)
    xy = (rays[..., :2]/rays[..., 2:]+EDGE)/(2*EDGE)*8
    ids = [o['id'] for o in objects if o['category'] != 'BACKGROUND']
    bg_ids = [o['id'] for o in objects if o['category'] == 'BACKGROUND']
    masks = {arm: np.zeros((len(oid), 8, 8, 16), bool) for arm in SPECS}
    stats = dict(frames=len(oid), visible_candidates=0, uniform={}, background={})
    for t, frame in enumerate(oid):
        rng = np.random.default_rng(np.random.SeedSequence([SEED, unit, config, t, 99999]))
        uniform, us = fake_footprints(pool, rng, 10)
        bg, edge = background_support(frame, bg_ids)
        rng = np.random.default_rng(np.random.SeedSequence([SEED, unit, config, t, 99998]))
        structured, bs = fake_footprints(pool, rng, 10, bg, edge)
        for key, values in (('uniform', us), ('background', bs)):
            for k, v in values.items():
                stats[key][k] = stats[key].get(k, 0)+v
        objects_pixels = []
        for ident in ids:
            hit = frame == ident
            if not hit.any():
                continue
            stats['visible_candidates'] += 1
            rng = np.random.default_rng(np.random.SeedSequence([SEED, unit, config, t, int(ident)]))
            angle = rng.uniform(0, 2*np.pi)
            direction, drop = np.array([np.cos(angle), np.sin(angle)]), rng.random()
            objects_pixels.append((drop, {shift: to_pixels(xy[hit], direction, shift) for shift in (0., .25, .5, 1.)}))
        cache = {}
        for arm, (shift, dilation, drop_rate, nf, structured_flag) in SPECS.items():
            key = (shift, dilation, drop_rate)
            if key not in cache:
                pix = np.zeros((128, 128), bool)
                for drop, variants in objects_pixels:
                    if drop >= drop_rate:
                        pix |= variants[shift]
                cache[key] = to_zones(pix, dilation)
            zone = cache[key].copy()
            for fake in (structured if structured_flag else uniform)[:nf]:
                zone |= fake
            masks[arm][t] = zone[..., None]
        direct = np.isin(frame, ids).any(-1)
        if not np.array_equal(masks['G1'][t, :, :, 0], direct):
            raise AssertionError('G1 changed relative to original angular footprint')
    return masks, stats


def temporal_mask(cells, poses, g):
    """t-2/t-1 two-hit association; no current/future observation or oracle."""
    import torch
    from cnh_track_a_readout import WIDTH
    centers = g._orig.mean(1)
    local = torch.zeros_like(cells)
    accepted = []
    def angular(pts):
        return (pts[:, :2]/pts[:, 2:3].clamp_min(1e-12)+g.EDGE)/(2*g.EDGE)*8
    for i in range(2, len(cells)):
        old = centers[cells[i-2].flatten()]
        newer = centers[cells[i-1].flatten()]
        if not len(old) or not len(newer):
            accepted.append(0)
            continue
        rel = torch.linalg.inv(poses[i-1]) @ poses[i-2]
        moved = old @ rel[:3, :3].T + rel[:3, 3]
        r_old, r_moved, r_new = old.norm(dim=1), moved.norm(dim=1), newer.norm(dim=1)
        approaching = (r_old-r_moved >= .01) & (moved[:, 2] > 0)
        angular_ok = (angular(newer)[:, None]-angular(moved)[None]).abs().amax(-1) <= .5
        range_ok = (r_new[:, None]-r_moved[None]).abs() <= WIDTH
        decreasing = r_new[:, None] <= r_old[None]+.5*WIDTH
        keep = (angular_ok & range_ok & decreasing & approaching[None]).any(1)
        points = newer[keep]
        accepted.append(int(keep.sum()))
        rel = torch.linalg.inv(poses[i]) @ poses[i-1]
        points = points @ rel[:3, :3].T + rel[:3, 3]
        xy = angular(points)
        valid = (points[:, 2] > 0) & ((xy >= 0) & (xy < 8)).all(1)
        rc = xy[valid].floor().long()
        local[i, rc[:, 1], rc[:, 0], :] = True
    return local, dict(candidate_cells=int(cells.sum()), matched_cells=sum(accepted), mask_cells=int(local.sum()))


def sequence_scores(hist, ambient, bias, tq, noisy, masks):
    import torch
    import torch.nn.functional as F
    import cnh_track_a_gpu_readout as g
    from cnh_scan_development import WINDOWS
    n = len(hist)
    r = g.T(hist)-g.T(bias)
    v = 16*g.T(ambient)[..., None]+g.T(bias).clamp_min(0)
    rf, vf = r.reshape(n, 1024), v.reshape(n, 1024)
    vv = v.reshape(n, 8, 8, 16)
    support = (g.query_weights(torch.as_tensor(tq, dtype=g.D64, device=g.DEV)) >= .75).reshape(n, 6, 8, 8, 16)
    pairs = [(i, j) for i in range(1, n) for j in range(max(0, i-3), i)]
    I = torch.tensor([i for i, j in pairs], device=g.DEV)
    J = torch.tensor([j for i, j in pairs], device=g.DEV)
    p = torch.as_tensor(noisy, dtype=g.D64, device=g.DEV)
    A = g.transport(torch.linalg.inv(p[I]) @ p[J], 1).to(g.DT)
    total = rf.clone().index_add_(0, I, torch.bmm(A, rf[J].unsqueeze(-1)).squeeze(-1)).reshape(n, 8, 8, 16)
    At = A.transpose(1, 2).reshape(len(pairs)*1024, 1, 8, 8, 16)
    out = {arm: torch.full((n, 6), -float('inf'), device=g.DEV, dtype=g.DT) for arm in ARMS}
    out['G0'].fill_(-50.)
    zs, admissible = {}, {}
    cells = torch.zeros((n, 8, 8, 16), dtype=torch.bool, device=g.DEV)
    for shape in WINDOWS:
        size = int(np.prod(shape))
        c = F.avg_pool3d(At, shape, stride=1)*size
        c = c.reshape(len(pairs), 1024, *c.shape[-3:])
        var = g.boxsum(vv, shape).clone().index_add_(0, I, torch.einsum('ps,psxyz->pxyz', vf[J], c*c))
        z = g.boxsum(total, shape)/var.clamp_min(1e-9).sqrt()
        adm = g.boxsum(support.to(g.DT), shape) > size-.5
        zs[shape], admissible[shape] = z, adm
        hit = (z >= 2.5) & adm.any(1)
        cells |= F.conv_transpose3d(hit[:, None].to(g.DT), torch.ones((1, 1, *shape), device=g.DEV))[:, 0] > 0
        out['G0'] = torch.maximum(out['G0'], torch.where(adm, z[:, None], -float('inf')).flatten(2).max(-1).values)
    del A, At, c
    local, temporal = temporal_mask(cells, p, g)
    stack = torch.stack([torch.as_tensor(masks[a], device=g.DEV, dtype=g.DT) for a in SPECS]+[local.to(g.DT)])
    for shape in WINDOWS:
        allowed = g.boxsum(stack, shape) > 0
        for index, arm in enumerate(ARMS[1:]):
            adm = admissible[shape] & allowed[index, :, None]
            score = torch.where(adm, zs[shape][:, None], -float('inf')).flatten(2).max(-1).values
            out[arm] = torch.maximum(out[arm], score)
    return {arm: score.double().cpu().numpy() for arm, score in out.items()}, temporal


def score_unit(job):
    root, unit = Path(job[0]), job[1]
    wait_sensor(root, [unit])
    import torch
    torch.set_num_threads(1)
    import cnh_track_a_scale_evaluate as se
    import cnh_track_a_gpu_readout2 as reference
    from cnh_track_a_readout import noisy_poses
    if not torch.cuda.is_available():
        raise RuntimeError('GPU placement expected; no unrecorded CPU fallback')
    torch.cuda.reset_peak_memory_stats()
    se.sensor_module.FAMILY = FAMILY
    start = time.monotonic()
    split, records, step = se.unit_records(root/'geometry', root/'sensor', unit, -10, 1)
    if split not in ('calib', 'audit') or unit == 143:
        raise ValueError('Outside allowed data')
    bias = np.load(root/'bias.npy')
    pool = [np.asarray(x, int) for x in json.loads((root/'angular_templates.json').read_text())]
    data = json.loads((root/'geometry'/f'unit{unit:02d}'/f'unit{unit:02d}.json').read_text(encoding='utf-8-sig'))
    objects = {c['config']: c['objects'] for c in data['configs']}
    with np.load(root/'sensor'/f'unit{unit:02d}-mount-10-oracle.npz') as f:
        oid = f['object_id']  # No oracle range loaded.
    with np.load(root/'sensor'/f'unit{unit:02d}-mount-10-observations.npz') as f:
        if int(f['rate']) != 5:
            raise ValueError('Only 5 Hz inputs')
        config = f['config']
    scores, diagnostics, refs = {a: [] for a in ARMS}, [], []
    reference_file = root/'reference'/f'unit{unit:02d}.npz'
    saved_reference = None
    if reference_file.exists():
        with np.load(reference_file) as f:
            saved_reference = f['S2__noisy@0.75']
    for index, rec in enumerate(records):
        rows = np.flatnonzero(config == rec['config'])[::step]
        masks, stat = candidate_masks(oid[rows], objects[rec['config']], unit, rec['config'], pool)
        noisy = noisy_poses(rec['poses'], rec['ego_seed'], dt=.2)
        result, temporal = sequence_scores(rec['hist'], rec['ambient'], bias, rec['tq'], noisy, masks)
        for arm in ARMS:
            scores[arm].append(result[arm])
        stat['temporal'] = temporal
        diagnostics.append(stat)
        if saved_reference is None:
            original = reference.sequence_readouts(rec['hist'], rec['ambient'], bias, rec['poses'], rec['tq'], noisy, with_r4=False)
            refs.append(original['S2/noisy|0.75'])
    arrays = {arm: np.concatenate(value) for arm, value in scores.items()}
    baseline = np.concatenate(refs) if saved_reference is None else saved_reference
    if saved_reference is None:
        tmp = reference_file.with_suffix('.tmp.npz')
        np.savez_compressed(tmp, **{'S2__noisy@0.75': baseline}, split=np.array(split))
        tmp.replace(reference_file)
    err = float(np.abs(arrays['G0']-baseline).max())
    rel = float((np.abs(arrays['G0']-baseline)/np.maximum(1., np.abs(baseline))).max())
    if rel > 1e-5:
        raise ValueError(f'S2 reference mismatch {unit}: {err} / {rel}')
    for arm in ARMS[1:]:
        if np.any(arrays[arm] > arrays['G0']+1e-5):
            raise AssertionError(f'Masked score > G0: {arm}')
    extra = dict(config=np.repeat([r['config'] for r in records], 12), frame=np.tile(np.arange(12), len(records)),
                 labels=np.concatenate([r['labels'] for r in records]), witness=np.concatenate([r['witness'] for r in records]),
                 strata=se.strata_of(records), split=np.array(split), family=np.array(FAMILY),
                 G0_consistency_max_abs=err, G0_consistency_max_rel=rel)
    target = root/'scores'/f'unit{unit:02d}.npz'
    tmp = target.with_suffix('.tmp.npz')
    np.savez_compressed(tmp, **arrays, **extra)
    tmp.replace(target)
    (root/'scores'/f'unit{unit:02d}-diagnostics.json').write_text(json.dumps(diagnostics), encoding='utf-8')
    import psutil
    memory = psutil.Process().memory_info()
    return dict(unit=unit, seconds=time.monotonic()-start, G0_max_abs=err, G0_max_rel=rel,
                backend='cuda', device=torch.cuda.get_device_name(), peak_reserved_bytes=torch.cuda.max_memory_reserved(),
                host_peak_working_set=getattr(memory, 'peak_wset', memory.rss))


def wait_sensor(root, units):
    """Metadata is written last by the task sensor renderer: no partial NPZ read."""
    deadline = time.monotonic()+3600
    while not all((root/'sensor'/f'unit{u:02d}-mount-10.json').exists() for u in units):
        terminal = root/'terminal.json'
        if terminal.exists() and json.loads(terminal.read_text())['status'] == 'FAILED':
            raise RuntimeError('Sensor preparation failed; stop queued scoring')
        if time.monotonic() > deadline:
            raise TimeoutError('Sensor readiness exceeded one hour')
        time.sleep(2)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--root', type=Path, required=True)
    p.add_argument('--workers', type=int, default=1)
    p.add_argument('--units', nargs='+', type=int)
    a = p.parse_args()
    if a.root.name != FAMILY+'-dev-repaired':
        raise ValueError('Only authorized repaired-v2 task root')
    for name in ('reference', 'scores'):
        (a.root/name).mkdir(exist_ok=True)
    if not (a.root/'bias.npy').exists():
        wait_sensor(a.root, range(96, 128))
        print(json.dumps(build_calibration(a.root)), flush=True)
    units = [u for u in range(96, 192) if u != 143]
    chosen = a.units or units
    if not set(chosen) <= set(units):
        raise ValueError('Invalid units')
    jobs = [(str(a.root), u) for u in chosen if not (a.root/'scores'/f'unit{u:02d}.npz').exists()]
    receipt = a.root/'scoring_progress.json'
    progress = dict(status='running', total=len(chosen), complete=len(chosen)-len(jobs), workers=a.workers,
                    source_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest())
    start = time.monotonic()
    try:
        receipt.write_text(json.dumps(progress))
        with ProcessPoolExecutor(a.workers) as pool:
            for future in as_completed([pool.submit(score_unit, job) for job in jobs]):
                result = future.result()
                progress.update(complete=progress['complete']+1, last=result, elapsed_s=time.monotonic()-start)
                receipt.write_text(json.dumps(progress))
                print(json.dumps(result), flush=True)
        progress['status'] = 'complete'
    except BaseException as e:
        progress.update(status='failed', error=str(e))
        raise
    finally:
        receipt.write_text(json.dumps(progress, indent=2))


if __name__ == '__main__':
    main()
